<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"班级管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBanji"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"新闻资讯类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"生源地管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShengyuandi"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"所教专业管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShizililiang"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"校园风光类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXiaoyuanfengguang"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"院系管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYuanxi"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"留言板管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言板管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"新闻资讯信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"新闻资讯信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"师资力量管理",
                        "menuJump":"列表",
                        "tableName":"shizililiang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"师资力量留言管理",
                        "menuJump":"列表",
                        "tableName":"shizililiangLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"师资力量收藏管理",
                        "menuJump":"列表",
                        "tableName":"shizililiangCollection"
                    }
                ],
                "menu":"师资力量管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"单页数据管理",
                        "menuJump":"列表",
                        "tableName":"singleSeach"
                    }
                ],
                "menu":"单页数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"校园风光管理",
                        "menuJump":"列表",
                        "tableName":"xiaoyuanfengguang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"校园风光留言管理",
                        "menuJump":"列表",
                        "tableName":"xiaoyuanfengguangLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"校园风光收藏管理",
                        "menuJump":"列表",
                        "tableName":"xiaoyuanfengguangCollection"
                    }
                ],
                "menu":"校园风光管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "报表",
                            "删除"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"xuesheng"
                    }
                ],
                "menu":"学生管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"留言板管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"留言板管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"新闻资讯信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"新闻资讯信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"师资力量管理",
                        "menuJump":"列表",
                        "tableName":"shizililiang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"师资力量留言管理",
                        "menuJump":"列表",
                        "tableName":"shizililiangLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"师资力量收藏管理",
                        "menuJump":"列表",
                        "tableName":"shizililiangCollection"
                    }
                ],
                "menu":"师资力量管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"校园风光管理",
                        "menuJump":"列表",
                        "tableName":"xiaoyuanfengguang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"校园风光留言管理",
                        "menuJump":"列表",
                        "tableName":"xiaoyuanfengguangLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"校园风光收藏管理",
                        "menuJump":"列表",
                        "tableName":"xiaoyuanfengguangCollection"
                    }
                ],
                "menu":"校园风光管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"学生",
        "tableName":"xuesheng"
    }
];

var hasMessage = '';
